on:
  pull_request:
    types: [closed]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Zip application code
      run: |
        # Change directory to the root of the repository
        cd .

        # Zip the entire repository
        zip -r webapp.zip .

    - name:  create env file
      run: |
          echo "export SERVER_PORT=${{ secrets.SERVER_PORT }}" >> ~/development.env
          echo "export DATABASE=${{ secrets.DATABASE }}" >> ~/development.env
          echo "export DATABASE_SYS=${{ secrets.DATABASE_SYS }}" >> ~/development.env
          echo "export PORT=${{ secrets.PORT }}" >> ~/development.env
          echo "export HOST=${{ secrets.HOST }}" >> ~/development.env
          echo "export PASSWORD=${{ secrets.PASSWORD }}" >> ~/development.env
          echo "export USER=${{ secrets.USER }}" >> ~/development.env

    - name: Setup Packer
      uses: hashicorp/setup-packer@v0.2.0

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Initiate Packer template
      run: packer init .

    - name: Validate Packer template
      run: packer validate .

    - name: Build Packer template
      run: packer build .

    