name: Integration Testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: Arpitha
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cloud_arpitha
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Install Dependencies
        run: npm install
      
      - name: Wait for PostgreSQL to be ready
        run: |
          timeout=60
          until pg_isready -h localhost -p 5432 -U postgres; do
            timeout=$(($timeout - 1))
            if [ $timeout -eq 0 ]; then
              echo "PostgreSQL not ready, exiting..."
              exit 1
            fi
            sleep 1
          done
      
      - name: Run Integration Tests
        run: npm run test
