name: integration testing api
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    api-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                    POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: npm ci

            - name: API testing
              run: npm test
              env:
                  PGUSER: ${{ secrets.POSTGRES_USER }}
                  PGHOST: ${{ secrets.POSTGRES_HOST }}
                  PGDATABASE: ${{ secrets.POSTGRES_DB }}
                  PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                  PGPORT: ${{ secrets.POSTGRES_DB_PORT }}
                  PGDIALECT: ${{ secrets.POSTGRES_DB_DIALECT }}
                  APP_PORT: ${{ secrets.NODE_APP_PORT }}
